[2023-10-22T20:25:32.948+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_score.get_data manual__2023-10-22T16:25:31.000989+00:00 [queued]>
[2023-10-22T20:25:32.950+0400] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_score.get_data manual__2023-10-22T16:25:31.000989+00:00 [queued]>
[2023-10-22T20:25:32.950+0400] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-22T20:25:32.958+0400] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-10-22 16:25:31.000989+00:00
[2023-10-22T20:25:32.959+0400] {standard_task_runner.py:57} INFO - Started process 7067 to run task
[2023-10-22T20:25:32.962+0400] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'iris_score', 'get_data', 'manual__2023-10-22T16:25:31.000989+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/iris_score.py', '--cfg-path', '/tmp/tmpnvpdwn0q']
[2023-10-22T20:25:32.963+0400] {standard_task_runner.py:85} INFO - Job 7: Subtask get_data
[2023-10-22T20:25:33.041+0400] {task_command.py:416} INFO - Running <TaskInstance: iris_score.get_data manual__2023-10-22T16:25:31.000989+00:00 [running]> on host primary
[2023-10-22T20:25:33.068+0400] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='iris_score' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T16:25:31.000989+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T16:25:31.000989+00:00'
[2023-10-22T20:25:33.069+0400] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-22T20:25:33.069+0400] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/pyretttt/repos/mlops3/scripts/get_data.py']
[2023-10-22T20:25:33.073+0400] {subprocess.py:86} INFO - Output:
[2023-10-22T20:25:33.526+0400] {subprocess.py:93} INFO - /home/pyretttt/repos/mlops3/env/lib/python3.10/site-packages/pydantic/_internal/_fields.py:128: UserWarning: Field "model_server_url" has conflict with protected namespace "model_".
[2023-10-22T20:25:33.527+0400] {subprocess.py:93} INFO - 
[2023-10-22T20:25:33.527+0400] {subprocess.py:93} INFO - You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
[2023-10-22T20:25:33.527+0400] {subprocess.py:93} INFO -   warnings.warn(
[2023-10-22T20:25:33.530+0400] {subprocess.py:93} INFO - /home/pyretttt/repos/mlops3/env/lib/python3.10/site-packages/pydantic/_internal/_config.py:317: UserWarning: Valid config keys have changed in V2:
[2023-10-22T20:25:33.530+0400] {subprocess.py:93} INFO - * 'schema_extra' has been renamed to 'json_schema_extra'
[2023-10-22T20:25:33.530+0400] {subprocess.py:93} INFO -   warnings.warn(message, UserWarning)
[2023-10-22T20:25:33.556+0400] {subprocess.py:93} INFO - 2023/10/22 20:25:33 INFO mlflow.tracking.fluent: Experiment with name 'get_model' does not exist. Creating a new experiment.
[2023-10-22T20:25:34.115+0400] {subprocess.py:97} INFO - Command exited with return code 0
[2023-10-22T20:25:34.131+0400] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=iris_score, task_id=get_data, execution_date=20231022T162531, start_date=20231022T162532, end_date=20231022T162534
[2023-10-22T20:25:34.160+0400] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T20:25:34.314+0400] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
